### ISSUE TITLE
Tautilli Integration Instructions

### ISSUE THREAD

**Issue by danz0l** [airship-david/Trailer-Downloader#27]
Following the instructions as to add download.py to Tautilli to automate trailer downloads i seem to stumble on this part of the instructions

>  Next, go to the triggers tab and check the box for "Recently Added" and then go to the conditions tab and add a condition to only fire when "media type is movie"

I add "movie" manually as per instructions i.e.

Condition {1}
Media Type                    is                      movie
but the script never fires, even though my discord bots etc all function as they should ?

I have noted that the end box is a drop down. Should there be selectable items there where i could select movies as it has nothing in my Tautilli installation

**Comment by airship-david** [comment]
Do your settings look like the screenshots below?

Triggers Tab
<img width="720" alt="Screen Shot 2019-06-20 at 2 20 46 PM" src="https://user-images.githubusercontent.com/28158751/59875586-bd192600-9366-11e9-8436-02b611c8f948.png">

Conditions Tab
<img width="717" alt="Screen Shot 2019-06-20 at 2 20 06 PM" src="https://user-images.githubusercontent.com/28158751/59875612-caceab80-9366-11e9-9508-42d7ed05094f.png">

Arguments Tab
<img width="695" alt="Screen Shot 2019-06-20 at 2 20 36 PM" src="https://user-images.githubusercontent.com/28158751/59875634-db7f2180-9366-11e9-8274-415a8a9f9d4b.png">

**Comment by airship-david** [comment]
I had to enter the word "movie" manually as well.

**Comment by danz0l** [comment]
yes David i had this EXACTLY as yours apart from the nopythonpath in the script arguments. My bot fires up telling me the films have been added to plex, but the script doesn't or indeed outputs anything in the logs

**Comment by danz0l** [comment]
is "movie" related to the plex library it will go into ? If so then im wondering if this is the issue as mine is "Films". I mean how does Tautilli know what media type it is ?

**Comment by airship-david** [comment]
Please try it with nopythonpath. I can't remember why but I couldn't get it to work without doing that. Some sort of conflict.

Per Tautulli's documentation:
"Tautulli will enhance the PYTHONPATH variable with the path of its own bundled libraries, allowing scripts to use any of the bundled libraries without the user needing to have installed them system wide. However, this means that the bundled versions take priority. If you want to disable this feature simply prepend nopythonpath to the script arguments."

For the "movie" question... Yes this is the type of plex library that will trigger the script. When something goes into a library where the type is movie it will fire. Otherwise, the script will be ignored. In Plex you chose a library type like below for your "Films" yeah?

<img width="529" alt="Screen Shot 2019-06-20 at 2 37 52 PM" src="https://user-images.githubusercontent.com/28158751/59876434-43cf0280-9369-11e9-92ed-986eb4eead79.png">

**Comment by danz0l** [comment]
ah i think its some type of permission issue.


2019-06-20 20:37:48 | INFO | Tautulli Notifiers :: Script notification sent.
-- | -- | --
2019-06-20 20:37:48 | ERROR | Tautulli Notifiers :: Script error:     ERROR: unable to open for writing: [Errno 13] Permission denied: '/home/Trailer-Downloader/downloads/Trailer.f134.mp4.part'
2019-06-20 20:37:48 | DEBUG | Tautulli Notifiers :: Subprocess returned with status code 0.
2019-06-20 20:37:45 | INFO | Tautulli Notifiers :: Script notification sent.
2019-06-20 20:37:45 | ERROR | Tautulli Notifiers :: Script error:     Traceback (most recent call last):         File "/home/Trailer-Downloader/download.py", line 322, in <module>             main()         File "/home/Trailer-Downloader/download.py", line 274, in main             file = appleDownload('https://trailers.apple.com/'+result['location'], settings['resolution'], arguments['directory'], filename)         File "/home/Trailer-Downloader/download.py", line 177, in appleDownload             downloadFile(trailer_url['url'], directory, filename)         File "/home/Trailer-Downloader/download.py", line 163, in downloadFile             with open(os.path.split(os.path.abspath(__file__))[0]+'/downloads/'+filename, 'wb') as local_file_handle:     IOError: [Errno 13] Permission denied: u'/home/Trailer-Downloader/downloads/Trailer.mp4'
2019-06-20 20:37:45 | DEBUG | Tautulli Notifiers :: Subprocess returned with status code 1.
2019-06-20 20:37:41 | DEBUG | Tautulli Notifiers :: Executing script in a new thread.
2019-06-20 20:37:41 | DEBUG | Tautulli Notifiers :: Full script is: ['python', u'/home/Trailer-Downloader/download.py', '--title', 'Stealing Beauty', '--year', '1996', '--file', '/media/usb-drive2/Movies/Stealing Beauty (1996)/Stealing Beauty (1996) WEBDL-1080p x265.AAC.mkv']
2019-06-20 20:37:41 | DEBUG | Tautulli Notifiers :: Trying to run notify script, action: created, arguments: [u'nopythonpath', u'--title', u'Stealing Beauty', u'--year', u'1996', u'--file', u'/media/usb-drive2/Movies/Stealing Beauty (1996)/Stealing Beauty (1996) WEBDL-1080p x265.AAC.mkv']
2019-06-20 20:37:41 | DEBUG | Tautulli Notifiers :: Executing script in a new thread.
2019-06-20 20:37:41 | DEBUG | Tautulli Notifiers :: Full script is: ['python', u'/home/Trailer-Downloader/download.py', '--title', 'Broken City', '--year', '2013', '--file', '/media/usb-drive2/Movies/Broken City (2013)/Broken City (2013) Bluray-1080p x265.AC3.mkv']
2019-06-20 20:37:41 | DEBUG | Tautulli Notifiers :: Trying to run notify script, action: created, arguments: [u'nopythonpath', u'--title', u'Broken City', u'--year', u'2013', u'--file', u'/media/usb-drive2/Movies/Broken City (2013)/Broken City (2013) Bluray-1080p x265.AC3.mkv']
2019-06-20 20:37:41 | INFO | Tautulli NotificationHandler :: Preparing notification for notifier_id 7.
2019-06-20 20:37:41 | INFO | Tautulli Notifiers :: Discord notification sent.
2019-06-20 20:37:41 | INFO | Tautulli NotificationHandler :: Preparing notification for notifier_id 7.

**Comment by danz0l** [comment]
seems like it is firing when plex updates but cant write to the Trailer directory for export due to write permission issues in linux.

**Comment by airship-david** [comment]
Oh strange. Maybe try running chmod -R 777 /home/Trailer-Downloader. Shouldn't be inherently dangerous if that directory isn't exposed to anything.

**Comment by danz0l** [comment]
i think i see the issue. Tautilli is running under its own username and not my main one, those has no permission or ownership to right to the Trailer Downloader directory, thus throwing the error

**Comment by airship-david** [comment]
Ah yeah that makes a lot of sense. Going to go ahead and close this issue but we can reopen it if changing ownership or locations doesn't work.
